### PR TITLE
remove echo JSESSIONID

### PR DESCRIPTION
**Pull request by onealbao**

### CODE REVIEW

**Comment by onealbao** [comment]
@baxpr it seems my recent commit was pushed to this pull request. The edit was about adding two separate job templates files for the two job templates. The difference are name of SBATCH --account.

**Comment by baxpr** [comment]
Looks good to me! I often find it helpful to make a different branch+PR for each different purpose. But, it doesn't matter much.

Where do you tell ldax to use the right job template now that there are two?

**Comment by onealbao** [comment]
I see, once the PR is done, we can also delete the branch (which github always pop a message about it:-)). Sounds like it a good plan. 

To tell ldax using different job template, we need to change the value of 'job_template=' in ${HOME}/.dax_settings.ini
This file is not under version control. Well it has password of vuiis.cci@gmail.com, maybe we should not put it to any Git repository like dax_credential/ldax_credential currently does.

**Comment by baxpr** [comment]
Oh, that's right. Please go ahead and merge/pull this PR, then update the dax settings files by hand. You're right, we aren't keeping .dax_settings.ini in any repo.

**Pull request merged**
